name: Build and Start Backend

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-start-backend:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.22.5" # Укажите нужную версию Go

            - name: Install dependencies
              run: go mod tidy # Устанавливает зависимости

            - name: Build project
              run: go build -o backend . # Сборка проекта в исполняемый файл

            - name: Run project
              run: |
                  nohup ./backend > backend.log 2>&1 &
                  sleep 10
                  tail -n 100 backend.log  # Просмотр последних 100 строк логов
